### ISSUE TITLE
Problem with referencing one scoped service in another

### ISSUE THREAD

**Issue by ashkansirous** [Azure/azure-functions-dotnet-extensions#19]
I have a Entity framework DatabaseContext that I like to add also as my DatabaseContextBase.
 DatabaseContext inherits from DatabaseContextBase and  DatabaseContextBase inherits from DbContext.

Here is how I've tried it:

In startup:

```
 services.AddDbContext<DatabaseContext>(options =>...);
services.AddScoped<DatabaseContextBase, DatabaseContext>(sp => sp.GetRequiredService<DatabaseContext>());
services.AddScoped<SomethingThatUsesDatabaseContext>();
services.AddScoped<SomethingThatUsesDatabaseContextBase>();

```
Then in the function I use those 2:

```
SomethingThatUsesDatabaseContext.DoSomething();
SomethingThatUsesDatabaseContextBase.DoSomethingElse();

```

The first one works fine but the second one fails with this exception:

> System.ObjectDisposedException
>   HResult=0x80131622
>   Message=Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
> Object name: 'DatabaseContext'.
>   Source=Microsoft.EntityFrameworkCore
>   StackTrace:
>    at Microsoft.EntityFrameworkCore.DbContext.CheckDisposed()
>    at Microsoft.EntityFrameworkCore.DbContext.AddRangeAsync(Object[] entities)
>    at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.AddRangeAsync(TEntity[] entities)
>    at SomethingThatUsesDatabaseContextBase
>    .<AddUnprocessedEvents>d__6.MoveNext() in 
>

**Comment by ashkansirous** [comment]
Just to explain more, my work around right now is like this:
```
private readonly DatabaseContext _databaseContext;
public Function1(DatabaseContext databaseContext)
{
  _databaseContext=databaseContext;
}
[FunctionName("function1")]
public async Task Run([ServiceBusTrigger(...)])
{
SomethingThatUsesDatabaseContext.DoSomething();
new SomethingThatUsesDatabaseContextBase(_databaseContext).DoSomethingElse();
}
```
And it works fine. The

**Comment by ashkansirous** [comment]
Any news on this one? 
No one even looked at it for 2 months

**Comment by t-l-k** [comment]
I mean this is pretty serious. 

Couldn't quite believe my eyes that I had `DbContext`'s being shared across invocations of functions. 

I'm amazed it worked this far (about 4.5 weeks development), but now we have a mixed bag of integration tests against `func.exe`, its falling over hard because of shared state between invocations, which should be scoped.

😭 😭 😭
