### ISSUE TITLE
Remaining incompatibility issues with .NET Core 3 and DependencyInjection

### ISSUE THREAD

**Issue by eliashdezr** [Azure/azure-functions-dotnet-extensions#36]
Taking @jeffhollan's [words](https://github.com/Azure/azure-functions-dotnet-extensions/issues/32#issuecomment-587167920) into action, this is the main issue I've seen not only on my personal projects, but elsewhere too.

### Error while running the functions via Visual Studio:
` Microsoft.Extensions.DependencyInjection.Abstractions: Unable to resolve service for type`

### Error while deployed on a brand new Function v3 app in Azure:
```cs
System.InvalidOperationException: Unable to resolve service for type 'Project.Hidden.Domain.Interfaces.Service.IAzureStorageService' while attempting to activate 'Project.Hidden.Serverless.Importacion.VerificarFunction'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.Azure.WebJobs.Host.Executors.DefaultJobActivator.CreateInstance[T](IServiceProvider serviceProvider) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\DefaultJobActivator.cs:line 37
   at Microsoft.Azure.WebJobs.Host.Executors.DefaultJobActivator.CreateInstance[T](IFunctionInstanceEx functionInstance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\DefaultJobActivator.cs:line 32
   at Microsoft.Azure.WebJobs.Host.Executors.ActivatorInstanceFactory`1.<>c__DisplayClass1_1.<.ctor>b__0(IFunctionInstanceEx i) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\ActivatorInstanceFactory.cs:line 20
   at Microsoft.Azure.WebJobs.Host.Executors.ActivatorInstanceFactory`1.Create(IFunctionInstanceEx functionInstance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\ActivatorInstanceFactory.cs:line 26
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.CreateInstance(IFunctionInstanceEx functionInstance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 44
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ParameterHelper.Initialize() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 846
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsyncCore(IFunctionInstanceEx functionInstance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 116
```
### Only working when...
If I run the project from the cli with `func start --build`, all the functions work, but it logs the following errors on the console for each function:
```log
[2020-02-18 12:30:49 AM] Error indexing method 'ImportarcionVerificarFunction'
[2020-02-18 12:30:49 AM] Microsoft.Azure.WebJobs.Host: Error indexing method 'ImportarcionVerificarFunction'. System.Private.CoreLib: Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified. System.Private.CoreLib: Could not load the specified file.
[2020-02-18 12:30:49 AM] Function 'ImportarcionVerificarFunction' failed indexing and will be disabled.
..
..
[2020-02-18 12:30:49 AM] The 'ImportarcionFinalizarFunction' function is in error: Unable to load one or more of the requested types.
[2020-02-18 12:30:49 AM] Could not load file or assembly 'netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
```

### My system setup and configurations
Everything worked fine until I migrated to .NET Core 3

```
 - Visual Studio 16.5.0 Preview 2
 - azure-functions-core-tools@3.0.2106
 - npm@v13.2.0
```
`global.json`
```json
{
  "sdk": {
    "version": "3.1.101"
  }
}
```

`.csproj`
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="3.1.1" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.3" />
    <PackageReference Include="Utf8Json" Version="1.3.7" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Project.Hidden.Data\Project.Hidden.Data.csproj" />
    <ProjectReference Include="..\Project.Hidden.Domain\Project.Hidden.Domain.csproj" />
    <ProjectReference Include="..\Project.Hidden.Services\Project.Hidden.Services.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

`Startup.cs`
```csharp
using Microsoft.Azure.Functions.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection;
using Project.Hidden.Data;
using Project.Hidden.Domain.Interfaces.Repository;

namespace Project.Hidden.Functions
{
    public class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            builder.Services.AddSingleton<IAzureStorageService, AzureStorageService>();
        }
    }
}
```

`local.settings.json`
```json
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet",
    "FUNCTIONS_EXTENSION_VERSION": "~3"
  }
}
```

`host.json`
```json
{
  "version": "2.0",
  "healthMonitor": {
    "enabled": true,
    "healthCheckInterval": "00:00:10",
    "healthCheckWindow": "00:02:00",
    "healthCheckThreshold": 6,
    "counterThreshold": 0.80
  },
  "functionTimeout": "00:10:00"
}
```

**Comment by eliashdezr** [comment]
Here's a reproduction of the error using the examples listed in the official [documentation](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection).

Before I created this project, I ran the following command: 

` npm i -g azure-functions-core-tools@3 --unsafe-perm true`

And also updated to the latest version of VS: 
```
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.5.0 Preview 5.0
```

There are no compilation errors but when trying to hit the endpoint, I get this exception when running the function with Visual Studio:
```log
[2020-03-05 1:41:46 AM] Executed 'GetPosts' (Failed, Id=7fa531e7-ec70-46e0-be39-ad261aa6e527)
[2020-03-05 1:41:46 AM] Microsoft.Extensions.DependencyInjection.Abstractions: Unable to resolve service for type 'System.Net.Http.IHttpClientFactory' while attempting to activate 'MyNamespace.HttpTrigger'.
[2020-03-05 1:41:46 AM] An unhandled host error has occurred.
[2020-03-05 1:41:46 AM] Microsoft.Extensions.DependencyInjection.Abstractions: Unable to resolve service for type 'System.Net.Http.IHttpClientFactory' while attempting to activate 'MyNamespace.HttpTrigger'.
```

And this error when running from the command line (`func start --build`)
```log
[2020-03-05 1:02:36 AM] Executed 'GetPosts' (Failed, Id=633c9caf-76d5-471a-b0e2-19955ea99933)
[2020-03-05 1:02:36 AM] System.Private.CoreLib: Could not load file or assembly 'Microsoft.Extensions.Http, Version=3.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified. System.Private.CoreLib: Could not load the specified file.
```

[FunctionsDependencyInjection.zip](https://github.com/Azure/azure-functions-dotnet-extensions/files/4290392/FunctionsDependencyInjection.zip)

**Comment by jeffhollan** [comment]
Thank you @eliashdezr this helps a ton.  I was able to use your zip and repro.  Now I'm digging into it some as I'm slightly confused as I just had DI working in v3 a few hours ago to update some other docs.  But appreciate you providing such a concrete repro

**Comment by jeffhollan** [comment]
@eliashdezr I was able to get your sample to work by using the Azure Functions SDK 3.0.3.  When I bump to 3.0.4 I do hit issues as well:

```xml
<!-- This one works -->
<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.3" />
```

Let me flag @paulbatum @brettsam as that just went out 4 days ago and appears something off there.

**Comment by brettsam** [comment]
The big difference between 3.0.3 and 3.04 is that we trim the output now -- @fabiocav, any ideas on this? Are we too aggressive with the trimming?

**Comment by Coops9** [comment]
This may help to debug the problem, I was having this exact issue and when comparing extensions.json after the upgrade to 3.0.4 it looked like this (missing any startup references)

```
{
  "extensions":[
  ]
}
```

**Comment by Coops9** [comment]
> The big difference between 3.0.3 and 3.04 is that we trim the output now -- @fabiocav, any ideas on this? Are we too aggressive with the trimming?

@brettsam This may help to debug the problem, I was having this exact issue and when comparing extensions.json after the upgrade to 3.0.4 it looked like this (missing any startup references)

```
{
  "extensions":[
  ]
}
```

**Comment by brettsam** [comment]
Yeah, extension metadata generation is completely broken in 3.0.4 -- I think we should hide it from nuget. Because Microsoft.Azure.WebJobs.Host isn't in the output folder anymore, all extensions fail to load and we fail to find them. This includes all bindings.

I see this in the build logs: 

    Unable to find fallback for assembly 'Microsoft.Azure.WebJobs.Host'. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Azure.WebJobs.Host, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

**Comment by brettsam** [comment]
Note that publishing *does work*. If I do `dotnet publish`, the extensions.json looks correct. 

I believe the issue is here -- this should look similar to the publish target right below it and happen after extensions are generated. https://github.com/Azure/azure-functions-host/blob/dev/tools/ExtensionsMetadataGenerator/src/ExtensionsMetadataGenerator/Targets/Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets#L30
