### ISSUE TITLE
NullReferenceException with 1.1.0 (Value cannot be null. (Parameter 'webJobsBuilderContext')

### ISSUE THREAD

**Issue by Socolin** [Azure/azure-functions-dotnet-extensions#51]
Hello,

After upgrading to the version 1.1.0 of `Microsoft.Azure.Functions.Extensions`  I'm getting a NullReferenceException when I try to start a function app from a Webjob project (I use this for starting the function app in tests)

Here a .zip with 2 projects to reproduce the problem
[repro.zip](https://github.com/Azure/azure-functions-dotnet-extensions/files/5235506/repro.zip)

```
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'webJobsBuilderContext')
   at Microsoft.Azure.Functions.Extensions.DependencyInjection.FunctionsHostBuilderContext..ctor(WebJobsBuilderContext webJobsBuilderContext)
   at Microsoft.Azure.Functions.Extensions.DependencyInjection.DefaultFunctionsHostBuilderContext..ctor(WebJobsBuilderContext webJobsBuilderContext)
   at Microsoft.Azure.Functions.Extensions.DependencyInjection.FunctionsHostBuilder..ctor(IServiceCollection services, WebJobsBuilderContext webJobsBuilderContext)
   at Microsoft.Azure.Functions.Extensions.DependencyInjection.FunctionsStartup.Configure(WebJobsBuilderContext context, IWebJobsBuilder builder)
   at Microsoft.Azure.WebJobs.WebJobsBuilderExtensions.ConfigureStartup(IWebJobsStartup startup, WebJobsBuilderContext context, IWebJobsBuilder builder) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Hos
ting\WebJobsBuilderExtensions.cs:line 168
   at Microsoft.Azure.WebJobs.WebJobsBuilderExtensions.UseWebJobsStartup(IWebJobsBuilder builder, Type startupType, WebJobsBuilderContext context, ILoggerFactory loggerFactory) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsof
t.Azure.WebJobs.Host\Hosting\WebJobsBuilderExtensions.cs:line 111
   at Microsoft.Azure.WebJobs.WebJobsBuilderExtensions.UseWebJobsStartup(IWebJobsBuilder builder, Type startupType, ILoggerFactory loggerFactory) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Hosting\We
bJobsBuilderExtensions.cs:line 84
   at Microsoft.Azure.WebJobs.WebJobsBuilderExtensions.UseWebJobsStartup[T](IWebJobsBuilder builder, ILoggerFactory loggerFactory) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Hosting\WebJobsBuilderExt
ensions.cs:line 74
   at Microsoft.Azure.WebJobs.WebJobsBuilderExtensions.UseWebJobsStartup[T](IWebJobsBuilder builder) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Hosting\WebJobsBuilderExtensions.cs:line 69
   at test.Program.<>c.<Main>b__0_0(IWebJobsBuilder webJobsBuilder) in D:\dev\git\rider\repro-jetbrains\ConsoleApplication2\test\Program.cs:line 39
   at Microsoft.Extensions.Hosting.WebJobsHostBuilderExtensions.<>c__DisplayClass2_0.<ConfigureWebJobs>b__0(HostBuilderContext context, IWebJobsBuilder b) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\H
osting\WebJobsHostBuilderExtensions.cs:line 27
   at Microsoft.Extensions.Hosting.WebJobsHostBuilderExtensions.<>c__DisplayClass5_0.<ConfigureWebJobs>b__1(HostBuilderContext context, IServiceCollection services) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJ
obs.Host\Hosting\WebJobsHostBuilderExtensions.cs:line 56
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at test.Program.Main(String[] args) in D:\dev\git\rider\repro-jetbrains\ConsoleApplication2\test\Program.cs:line 45
   at test.Program.<Main>(String[] args)
```

The problem seems to come from `FunctionsStartup` that now implements `IWebJobsStartup2`
So when building the host:
```
			var builder = new HostBuilder()
				.UseEnvironment(environment)
				.ConfigureWebJobs(webJobsBuilder =>
				{
					webJobsBuilder
						.AddAzureStorageCoreServices()
						.UseWebJobsStartup<Startup>();
				})
```
`.UseWebJobsStartup<Startup>()` will ends up calling with `context = null` 

```
        private static void ConfigureStartup(IWebJobsStartup startup, WebJobsBuilderContext context, IWebJobsBuilder builder)
        {
            if (startup is IWebJobsStartup2 startup2)
            {
                startup2.Configure(context, builder);
            }
            else
            {
                startup.Configure(builder);
            }
        }
```

and then crash in constructor of `FunctionsHostBuilder` 

on this line
```
      this.Context = (FunctionsHostBuilderContext) new DefaultFunctionsHostBuilderContext(webJobsBuilderContext);
```

**Comment by brettsam** [comment]
I'm investigating. To be clear, this is when trying to use a `FunctionsStartup` as the type for `UseWebJobsStartup<T>()`, correct? Your function app runs correctly, but this test does not?

**Comment by brettsam** [comment]
Ahh, yes, we don't handle null context there. Workaround for now is for you to call this from your test:

`UseWebJobsStartup(typeof(Startup), new WebJobsBuilderContext(), NullLoggerFactory.Instance);`

**Comment by Socolin** [comment]
> I'm investigating. To be clear, this is when trying to use a `FunctionsStartup` as the type for `UseWebJobsStartup<T>()`, correct? Your function app runs correctly, but this test does not?

That's right, the function app on it's own is working, but for testing purpose when I start it through the webjob sdk it fail.

Thanks for the workaround, I'll try it when I find some times.

**Comment by LayZeeDK** [comment]
I experienced a similar error when updating to `Microsoft.Azure.Functions.Extensions` version 1.1.0

What fixed issues in my case:
- Update .NET Core SDK to version 3.1.402.
- Update Azure Functions Core Tools to version 3.0.2881 or 3.0.2912.
- Update `Microsoft.Azure.WebJobs` to version 3.0.19.
- Update `Microsoft.Azure.WebJobs.Extensions.ServiceBus` to version 4.1.2.
- Update `Microsoft.NET.Sdk.Functions` to version 3.0.9.

Especially the Azure Functions Core Tools update seemed to fix the issue in Azure Pipelines.

**Comment by brettsam** [comment]
@LayZeeDK -- Moving the Core Tools is likely what fixed it for you. The docs on the new features in 1.1.0 call out that you need a newer version of the Host, but I realize that's not entirely clear unless you happened to go look up the release notes for 1.1.0. Linking them here for anyone else that comes across this.
- https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection#customizing-configuration-sources
- https://github.com/Azure/azure-functions-dotnet-extensions/releases/

**Comment by doublej974** [comment]
Hi @brettsam. I try all what was mentionned in @LayZeeDK post but for me didn't solve the issue.

and don't find where to put UseWebJobsStartup(typeof(Startup), new WebJobsBuilderContext(), NullLoggerFactory.Instance);

Can you help? 

Thanks

`
[assembly: FunctionsStartup(typeof(SecPermCtrl.Startup))]
namespace SecPermCtrl
{
    /////////////////////////////////////////////////////
    /// class Startup
    ///
    public class Startup : FunctionsStartup
    {
        /////////////////////////////////////////////////////
        /// Function Configure
        ///
        /// <summary>
        /// Configure Startup of the project
        /// </summary>
       public override void Configure(IFunctionsHostBuilder objFunctionsHostBuilder)
        {
            objFunctionsHostBuilder.Services.AddHttpClient<IAirwatchApiLibClient, AirwatchApiLibClient>(
                c_objHttpClient => c_objHttpClient.BaseAddress = new Uri(Environment.GetEnvironmentVariable("AirwatchBaseUrl"))
            )
                //Set 5 min as the lifetime for the HttpMessageHandler objects in the pool used for the Catalog Typed Client
                .SetHandlerLifetime(TimeSpan.FromMinutes(5))
                .AddPolicyHandler(PollyRetryPolicy.GetRetryPolicyRateLimit())
                .AddPolicyHandler(PollyRetryPolicy.GetCircuitBreakerPolicy());

            objFunctionsHostBuilder.Services.AddSingleton<IAzureBlobStorage, AzureBlobStorage>();
        }
    }
}
`

**Comment by i9hdkill** [comment]
Updating Azure Functions Core Tools did the trick for me aswell

**Comment by kashimiz** [comment]
Hi @Socolin, it looks like this has been fixed with the latest Core Tools release. Could you upgrade and let us know if you're still experiencing this issue?

**Comment by Socolin** [comment]
Hello,

I still have the same problem. I don't understand why you are speaking about the Core Tools, since the example and the repro is run as a Webjob so it does not use this.

**Comment by LayZeeDK** [comment]
Azure Functions use web jobs for startup, host context, and more.
